apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/vkhtech/catalog-service/k8s?ref=4217776d767f084ca96082d17090ca30f1e9c0f8

patchesStrategicMerge:
- patch-env.yml
- patch-resources.yml
- patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: catalog-config

images:
- name: catalog-service
  newName: ghcr.io/vkhtech/catalog-service
  newTag: 4217776d767f084ca96082d17090ca30f1e9c0f8

replicas:
  - name: catalog-service
    count: 2